<?php

class WorkLogTableSeeder extends Seeder {
	public function run()
	{
		DB::table('work_logs')->delete();
//		$ticket = Ticket::where('owner_id', '=', 'jeff')->where('description', '=', 'Construct UI wireframes')->get()->first();
		
//		$user = User::where('username', '=', 'jeff')->get()->first();

		$mysqli = new mysqli( "localhost", "root", "root", "RandomFruit");


		$result = $mysqli->query("select t.id from tickets t join users u on t.owner_id = u.id where t.title like 'Construct UI wireframes' and u.username like 'jeff'");
		$row = $result->fetch_assoc();
		$ticket_id = $row['id'];
		$result = $mysqli->query("select id from users where username like 'jeff'");
		$row = $result->fetch_assoc();
		$user_id = $row['id'];
		$work_log = WorkLog::create(array( 'ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 1, 'value' => 5));
		

$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Begin the user manual' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 10));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Begin the user manual' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 1));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Construct UI wireframes' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 1, 'value' => 7));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Construct UI wireframes' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 1, 'value' => 5));

$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Create a draft login page using Twitter Bootstrap.' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 7));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Create a prototype MySQL database implementing the draft ERD.' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 4));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Create and assign tasks through the end of the project.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 3.25));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Create and assign tasks through Week 2' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 1, 'value' => 4));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Create dashboards using Twitter Bootstrap' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 12));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Create dashboards using Twitter Bootstrap' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 2));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Create database models and seeders' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 4, 'value' => 8));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Create use cases for user profiles' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 0));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Create your personal Git repo.' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 0.5));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Create your personal Git repo.' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 0.5));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Database setup with table creation in provisioning script' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 4, 'value' => 1));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Document how to use the authentication system and how our webpage directory structure works.' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 1));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Document how to use the authentication system and how our webpage directory structure works.' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 4, 'value' => 2));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Document the version control process very thoroughly' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 1));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Draft a description of the different components and their interfaces for Design Document Part 1' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 3));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Draft a description of the different components and their interfaces for Design Document Part 1' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 0));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Draft class diagrams for each component showing the classes to be developed (or used) and their relationship.' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 0));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Draft entity-relationship diagram' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 1, 'value' => 4));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Draft entity-relationship diagram' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 3));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Draft entity-relationship diagram' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 1, 'value' => 0));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Draft entity-relationship diagram' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 4));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Draft epic implementation: Instructor can create a course' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 4, 'value' => 10));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Draft epic implementation: Instructor/student can edit a task.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 4, 'value' => 7));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Draft epic implementation: Instructor/student can log in.' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 4, 'value' => 10));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Draft epic implementation: Random Fruit supports burndown charts.' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 4, 'value' => 10));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Draft sequence diagrams showing the message flow for each use-case (or user story).' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 0.25));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Draft sequence diagrams showing the message flow for each use-case (or user story).' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 12));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Draft state diagrams for classes that have states.' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 0));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Elaboration phase artifacts' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 5, 'value' => 10));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Elaboration phase artifacts' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 5, 'value' => 10));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Elaboration phase artifacts' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 5, 'value' => 10));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Elaboration phase artifacts' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 5, 'value' => 10));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Elaboration phase artifacts' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 5, 'value' => 10));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Figure out how and whether to use https' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 1, 'value' => 1));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Finalize Design Document Part 1.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 4, 'value' => 2));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Finalize the entity-relationship diagram.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 2));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Hook in the login page to the authentication system.' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 7));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Hook in the login page to the authentication system.' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 4, 'value' => 2));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'HTML code for initial mock-up' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 1, 'value' => 3));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor can create a course' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 9, 'value' => 2));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor can create a course' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 9, 'value' => 5));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor can create a course' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 9, 'value' => 5));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor can modify a course' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 9, 'value' => 5));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor can modify a course' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 9, 'value' => 5));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can create a task.' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 3));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can create a task.' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 7, 'value' => 15));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can create a task.' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 4));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can create a task.' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 7, 'value' => 5));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can create a task.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 4));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can create a task.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 7, 'value' => 12));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can create a task.' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 4));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can create a task.' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 7, 'value' => 15));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can create a task.' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 4));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can create a task.' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 7, 'value' => 8));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can edit a task.' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 3));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can edit a task.' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 7, 'value' => 8));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can edit a task.' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 3));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can edit a task.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 3));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can edit a task.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 7, 'value' => 2));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can edit a task.' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 3));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can edit a task.' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 3));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can edit a task.' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 7, 'value' => 4));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can edit fields.' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 7, 'value' => 5));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can edit fields.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 8, 'value' => 8));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can edit fields.' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 8, 'value' => 10));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can edit fields.' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 8, 'value' => 3));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can generate reports.' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 8, 'value' => 16));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can generate reports.' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 9, 'value' => 8));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can generate reports.' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 8, 'value' => 10));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can generate reports.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 8, 'value' => 3));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can generate reports.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 9, 'value' => 8));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can generate reports.' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 8, 'value' => 8));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can log in.' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 3));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can log in.' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 3));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can log in.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 3));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can log in.' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 3));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can log in.' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 3));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can search tasks.' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 9, 'value' => 2));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can search tasks.' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 7, 'value' => 5));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can search tasks.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 8, 'value' => 3));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can search tasks.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 9, 'value' => 6));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can search tasks.' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 7, 'value' => 5));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Implement epic: Instructor/student can search tasks.' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 8, 'value' => 3));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Make database able to serve tickets to front end' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 4, 'value' => 1));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Make it so local testing environments serve a web page.' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 5.5));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Make it so local testing environments serve a web page.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 0.25));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Make it so that everyones version control repo is integrated with Trac.' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 2));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Make it so that we can edit a web page served by Babyhuey.' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 4));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Make it so that we can edit a web page served by Babyhuey.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 0.25));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Move existing dash and ticket pages into blade templates' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 6, 'value' => 4));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Move Vagrant provisioner to shell script' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 6));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Read through Twitter Bootstrap documentation.' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 3));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Read through Twitter Bootstrap documentation.' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 4));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Revise Design Document Part 1 components' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 0));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Revise Design Document Part 1 components' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 4.5));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Revise Design Document Part 1 components' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 10));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Revise the draft ERD.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 2));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Revise the requirements specification, taking account of wireframes and mock-ups.' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 0.25));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Revise the requirements specification, taking account of wireframes and mock-ups.' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 0.25));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Revise the Software Development Plan.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 3, 'value' => 2.5));$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Revise the Software Development Plan.' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 4, 'value' => 1));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Set up a master Vagrant instance' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 1, 'value' => 8));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Set up Vagrant and Virtualbox on your local machine' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 1, 'value' => 2));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Set up Vagrant and Virtualbox on your local machine' and u.username like 'dave'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'dave'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 1, 'value' => 2));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Set up Vagrant and Virtualbox on your local machine' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 1, 'value' => 2));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Set up Vagrant and Virtualbox on your local machine' and u.username like 'greg'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'greg'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 1, 'value' => 2));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Set up Vagrant and Virtualbox on your local machine' and u.username like 'jeff'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'jeff'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 1, 'value' => 2));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Set up value reporting system' and u.username like 'doug'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'doug'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 1, 'value' => 4));
$result=$mysqli->query("select t.id from tickets t join users u on t.owner_id=u.id where t.title like 'Show everyone how to make wiki pages' and u.username like 'alex'"); $row=$result->fetch_assoc(); $ticket_id=$row['id']; $result=$mysqli->query("select id from users where username like 'alex'"); $row=$result->fetch_assoc(); $user_id=$row['id']; $work_log=WorkLog::create(array('ticket_id' => $ticket_id, 'user_id' => $user_id, 'week_id' => 2, 'value' => 1));





		$result->close();
		$mysqli->close();




	}
}
